debug: true

logging:
  level:
    org.springframework: INFO
    com.thoughtworks.xbyi.persona: DEBUG

server:
  port: 8088
  servlet:
    contextPath: /v1/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persona?serverTimezone=GMT%2B8
    username: root
#    password: persona
  jpa:
    properties:
      hibernate:
        ddl-auto=create:
        show_sql: true
        format_sql: true
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml